### ISSUE TITLE
mp4 validation problem.

### ISSUE THREAD

**Issue by sagdelen** [ruiquelhas/magik#11] opened 2016-03-24 06:17 UTC
I have tried to validate various mp4 files, got Bad Request error like:
`{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"file\" fails because [\"file\" type is unknown]",
  "validation": {
    "source": "payload",
    "keys": [
      "file"
    ]
  }`

Ftyp information (in Hex) of my sample set are:
1    -    [0x00, 0x00, 0x00, 0x14]
2    -    [0x00, 0x00, 0x00, 0x18]
3    -    [0x00, 0x00, 0x00, 0x1C]
4    -    [0x00, 0x00, 0x00, 0x20]

**Comment by ruiquelhas** [comment] 2016-03-24 10:09
This is a mix of a bug and an enhancement. The problem is that the validation only [accounts](https://github.com/ruiquelhas/magik/blob/master/signatures.json#L5) for a single `ftyp` and actually uses the incorrect file signature.

I'll give it a look later, but in the meanwhile, PRs are welcome.

**Comment by ruiquelhas** [comment] 2016-03-28 21:41
So, I thought a bit about this, and I'm not sure if the change is worth the hassle.

Judging by your error, I guess you are using one of the `hapi` validation packages that depend on `magik`. Since I'm also maintaining those packages, I was thinking about updating them to perform the validation using [file-type](https://github.com/sindresorhus/file-type), which hopefully will help.

I'm closing the issue for now, but feel free to re-open if you have something else to add.

Thanks.

**Closed as completed** 2016-03-28 21:41 UTC
Labels: bug, enhancement
